- src/models.py
- Update `rcParams`: `font.size = 15`; `lines.linewidth = 3`
- add new color blind friendly color scheme using the same names that are used throught this script
- function now uses object oriented figure plotting
- place legend outside of the axes
- remove right and top spine
- enable the grid
- both x and y ticks are specified by a number
- added options to get the figure and axis objects as return (backwards compatible)
> Update the function plotInfected from the class SEIRSAgeModel

- setup.py
@Beramos this will be requried in order to get https://github.com/UGentBiomath/COVID19-Model/issues/36 up and running with the proposed script. I know that this is not DRY with respect to the `environment.yml` file, but I do think that it won't be that much of an issue managing both the setup and environment.
> Add packacge dependencies to setup

- .github/workflows/deploy.yml
This pull request adds a build script for sphinx 
> add build script sphinc

- .github/workflows/deploy.yml
- README.md
> add link to documentation website in README

- src/covid19model/data/google.py
- src/covid19model/data/sciensano.py
- src/covid19model/models/models.py
@twallema as shortly discussed and according to the guidelines described in the [documentation](https://ugentbiomath.github.io/COVID19-Model/collaborate.html#using-data) I extracted the functions from `models.py` file and moved them to the `src/data` folder. 
Would be good to have as well:
- update of the [data README](https://github.com/UGentBiomath/COVID19-Model/tree/master/data) so others understand the source and existence of the data et
- add a docstring documentation to the `get_google_mobility_data` function for others and your future self
-  not just checkbox the PR template stating _I made sure all new and existing data sets have a description in the data/README.md file_ if not done as such. cfr. your new [UZ Gent](https://github.com/UGentBiomath/COVID19-Model/pull/43/files) :-) …
> Move data scripts to proper folder

- .github/CONTRIBUTING.rst
I've noticed some wrong references dus to copy pasting from my side earlier on. My excuses, this should fix the issue. Thanks to Daan R. for noticing!
> Hot fix wrong documentation reference

- docs/installation.md
* some minor correction in the documentation w.r.t. typesetting and installation instructions
> Feat doc update

- binder/postBuild
* add postbuild script for binder to install COVID model after build
> add postBuild script: compiling COVIDMODEL

- binder/postBuild
> hotfix postBuild (2): correct pip install command

- README.md
- docs/collaborate.md
- docs/index.rst
- Changes binder badges everywhere to the correct url
> Fix binder badge

- .github/CONTRIBUTING.rst
- docs/collaborate.md
Describe your fixes/additions/changes:
* update docs: What to do when adding python packages
* fixes some typos
resolves #71
> Update docs: what to do when adding python packages 

- docs/collaborate.md
- docs/installation.md
- correct pip install command for developer mode
- correct build directory sphinx
resolves #76
> Quick fix docs

- .gitignore
> Added sciensano dataset to gitignore

- docs/collaborate.md
Added an overview of the repo to the documentation website. Not sure what level of detail we want, but I guess it's not needed to put every individual file in the overview, @Beramos @stijnvanhoey ? Didn't build the documentation, so I hope lay-out will be ok ;-)
> update repo structure

- src/covid19model/data/parameters.py
- src/covid19model/data/polymod.py
Fix relative paths in parameters.py and polymod.py, so that the functions also work in notebooks located in other folders
> fix relative paths in order to read also from differently located notebooks

- src/covid19model/models/base.py
- src/covid19model/models/models.py
Update documentation of SEIRD model
> update function documentation

- .github/workflows/tests.yml
- src/tests/test_model.py
This adds the python model tests to Github Actions, to ensure that those keep working.
> Fix tests + run on github actions

- docs/collaborate.md
- docs/git_workflow.md
- docs/index.rst
This PR adds a new page with a proposed git workflow for collaborators in order to streamline as much as possible the way people contribute code.
> Workflow git

- data/README.md
- notebooks/JV-calibration-deterministic-arrondissements-parallel.ipynb
- src/covid19model/optimization/run_optimization.py
run_optimization.py: str(spatial_unit)
> Fix writing error

- src/covid19model/models/base.py
- src/covid19model/models/network.py
- src/covid19model/optimization/objective_fcns.py
- src/covid19model/visualization/optimization.py
@twallema and @mrollier:
additional changes of _excess_time, extraTime_ and _lag_time_ to warmup.
So anywhere you use any of these three terms in your notebooks, it will have to be changed to _**warmup**_ to avoid errors.
> change excess_time, extraTime and lag_time to warmup

- docs/models.md
> Fix minor mistakes in markdown

- hpc/run-calibration-WAVE2-4prev.sh
- src/covid19model/models/time_dependant_parameter_fncs.py
> Test and clarify python files

- src/covid19model/models/models.py
Small change to co-infection implementation in spatial model
> clarify dalpha state
